#!/bin/sh

set -e

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/streaming'
DIR_CONF='/etc/sds/connectors/streaming'
DIR_LOG='/var/log/sds/connectors/streaming'

cp /opt/sds/connectors/streaming/template/StreamingConnector /etc/init.d/stratio-connector-streaming
chmod 755 /etc/init.d/stratio-connector-streaming
chmod 755 /opt/sds/connectors/streaming/bin
chmod +x /opt/sds/connectors/streaming/bin/stratio-connector-streaming
chmod +x /etc/default/stratio-connector-streaming
export STREAMING_CONNECTOR_LIB=/opt/sds/connectors/streaming
export STREAMING_CONNECTOR_CONF="/etc/sds/connectors/streaming"

case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
   echo "entra"
    mkdir $DIR_LOG
  fi
echo "SALE"

  chown -R ${USER}:${GROUP} /opt/sds /etc/sds

  chown root:root /etc/init.d/stratio-connector-streaming
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod 775 $DIR_INSTALL
  chmod 775 $DIR_CONF
  chmod 775 $DIR_LOG
  
  update-rc.d stratio-connector-streaming defaults

  ;;
esac    


exit 0

