#!/bin/sh

set -e

#DEB

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/decision'
DIR_CONF='/etc/sds/connectors/decision'
DIR_CONF='/etc/sds/connectors/decision'
DIR_LOG='/var/log/sds/connectors/decision'


chmod 755 /etc/init.d/connector_decision
chmod 755 /opt/sds/connectors/decision/bin
chmod +x /opt/sds/connectors/decision/bin/stratio-connector-decision
chmod +x /etc/default/decision_connector
export DECISION_CONNECTOR_LIB=/opt/sds/connectors/decision
export DECISION_CONNECTOR_CONF="/etc/sds/connectors/decision"


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown root:root /etc/init.d/connector_decision
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod 775 $DIR_LOG

  sed -i 's!"$BASEDIR"/conf!/etc/sds/connectors/decision!g' /opt/sds/connectors/decision/bin/stratio-connector-decision

  update-rc.d connector_decision defaults
  ;;
esac    


exit 0

